### ISSUE TITLE
RQuantLib Installation Error - undefined symbol: _ZN8QuantLib4Bond10deepUpdateEv

### ISSUE THREAD

**Issue by singhalg** [eddelbuettel/rquantlib#145] opened 2020-01-21 20:10 UTC
```
$ sudo R CMD INSTALL --no-lock RQuantLib_0.4.11.tar.gz
* installing to library ‘/usr/lib64/R/library’
* installing *source* package ‘RQuantLib’ ...
** package ‘RQuantLib’ successfully unpacked and MD5 sums checked
staged installation is only possible with locking
** using non-staged installation
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -m64 -std=gnu++11 accepts -g... yes
checking how to run the C++ preprocessor... g++ -m64 -std=gnu++11 -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ -m64 -std=gnu++11 accepts -g... (cached) yes
checking for R... yes
checking for quantlib-config... yes
checking for Boost development files... yes
checking for minimal Boost version... yes
configure: creating ./config.status
config.status: creating src/Makevars
Completed configuration and ready to build.
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c affine.cpp -o affine.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c asian.cpp -o asian.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c barrier_binary.cpp -o barrier_binary.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c bermudan.cpp -o bermudan.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c bonds.cpp -o bonds.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c calendars.cpp -o calendars.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c curves.cpp -o curves.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c dates.cpp -o dates.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c daycounter.cpp -o daycounter.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c discount.cpp -o discount.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c hullwhite.cpp -o hullwhite.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c implieds.cpp -o implieds.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c modules.cpp -o modules.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c sabr.cpp -o sabr.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c schedule.cpp -o schedule.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c utils.cpp -o utils.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c vanilla.cpp -o vanilla.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c zero.cpp -o zero.o
g++ -m64 -std=gnu++11 -shared -L/usr/lib64/R/lib -Wl,-z,relro -o RQuantLib.so RcppExports.o affine.o asian.o barrier_binary.o bermudan.o bonds.o calendars.o curves.o dates.o daycounter.o discount.o hullwhite.o implieds.o modules.o sabr.o schedule.o utils.o vanilla.o zero.o -L/usr/lib64 -lQuantLib -fopenmp -L/usr/lib64/R/lib -lR
installing to /usr/lib64/R/library/RQuantLib/libs
** R
** data
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package ‘RQuantLib’
    finding HTML links ... done
    AffineSwaption                          html
    AmericanOption                          html
    AmericanOptionImpliedVolatility         html
    AsianOption                             html
    BarrierOption                           html
    BermudanSwaption                        html
    BinaryOption                            html
    BinaryOptionImpliedVolatility           html
    Bond                                    html
    BondUtilities                           html
    Calendars                               html
    CallableBond                            html
    ConvertibleBond                         html
    DiscountCurve                           html
    Enum                                    html
    EuropeanOption                          html
    EuropeanOptionArrays                    html
    EuropeanOptionImpliedVolatility         html
    FittedBondCurve                         html
    FixedRateBond                           html
    FloatingRateBond                        html
    ImpliedVolatility                       html
    Option                                  html
    SabrSwaption                            html
    Schedule                                html
    ZeroCouponBond                          html
    getQuantLibCapabilities                 html
    getQuantLibVersion                      html
    tsQuotes                                html
    vcube                                   html
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘RQuantLib’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/lib64/R/library/RQuantLib/libs/RQuantLib.so':
  /usr/lib64/R/library/RQuantLib/libs/RQuantLib.so: undefined symbol: _ZN8QuantLib4Bond10deepUpdateEv
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/lib64/R/library/RQuantLib’

```

===================
= QuantLib on RedHat ====
===================
```
$ ls -al /usr/lib64/libQuant*
lrwxrwxrwx 1 root root       20 Jan 13 14:45 /usr/lib64/libQuantLib.so -> libQuantLib.so.0.0.0
lrwxrwxrwx 1 root root       20 Jun 27  2019 /usr/lib64/libQuantLib.so.0 -> libQuantLib.so.0.0.0
-rwxr-xr-x 1 root root 22869000 Feb 27  2015 /usr/lib64/libQuantLib.so.0.0.0
```

Please suggest what other information could be useful. Thank you.

**Comment by eddelbuettel** [comment] 2020-01-21 21:14
Hm, what is you QuantLib version?

**Comment by singhalg** [comment] 2020-01-21 22:09
Thanks very much Dirk for taking this up. We are running RHEL7.7. We downloaded and installed QuantLib from CentOs repo here: https://centos.pkgs.org/7/epel-x86_64/

The version we have seems to be current. We'll nonetheless re-install the latest versions of both quantlib-config and quantlib-devel and retry installation of RQuantLib.



[  bin ] $ quantlib-config --version
1.17
[  bin ] $ quantlib-test-suite
Running 795 test cases...

Tests completed in 12 m 30 s


*** No errors detected

**Comment by eddelbuettel** [comment] 2020-01-21 22:15
Above my pay grade and comprehension.  Nobody 'hides' symbols.  Maybe you have an older quantlib hiding somewhere or something else.  I can only meekly suggest to check with the CRAN status page which shows success on Fedora too:  
https://cloud.r-project.org/web/checks/check_results_RQuantLib.html

You could subscribe to the [rquantlib list over at groups.io](https://groups.io/g/rquantlib and ask there.  Maybe somebody else is on CentOS--I am not, and I am out of suggestions.  :-/  Sorry.

**Comment by eddelbuettel** [comment] 2020-01-28 13:25
I think there is some disconnect on your end. While `quantlib-config` shows 1.17 (good!) you also have a 2015 date on the library: 

```
$ ls -al /usr/lib64/libQuant*
lrwxrwxrwx 1 root root       20 Jan 13 14:45 /usr/lib64/libQuantLib.so -> libQuantLib.so.0.0.0
lrwxrwxrwx 1 root root       20 Jun 27  2019 /usr/lib64/libQuantLib.so.0 -> libQuantLib.so.0.0.0
-rwxr-xr-x 1 root root 22869000 Feb 27  2015 /usr/lib64/libQuantLib.so.0.0.0
```

That 27 Feb 2015 on the actual library file may be an issue. On my machine:

```
edd@rob:~$ ls -l /usr/lib/libQ*
-rw-r--r-- 1 root root 144412696 Dec  3 18:47 /usr/lib/libQuantLib.a
lrwxrwxrwx 1 root root        20 Dec  3 18:47 /usr/lib/libQuantLib.so -> libQuantLib.so.0.0.0
lrwxrwxrwx 1 root root        20 Dec  3 18:47 /usr/lib/libQuantLib.so.0 -> libQuantLib.so.0.0.0
-rw-r--r-- 1 root root  37343072 Dec  3 18:47 /usr/lib/libQuantLib.so.0.0.0
edd@rob:~$ 
```

**Comment by singhalg** [comment] 2020-01-28 22:22
Our organizational limits us to use the packages provided by the RHEL7 distribution. The latest version of QuantLib provided by RHEL7 is 1.14, which seems to be incompatible with newer versions of RQuantLib. We are trying to find out another source of QuantLib1.17 that the organization will approve of.

**Comment by eddelbuettel** [comment] 2020-01-28 22:33
Thanks for confirming the root cause of your issue -- which is local to your setup so I will close this.  

Your issue ticket was somewhat misleading when it showed `quantlib-config` returning 1.17. 

Lastly, CRAN has older releases of RQuantLib to match the older QL you have.

**Closed by eddelbuettel** 2020-01-28 22:33 UTC
